INSERT INTO public."District"(id, type, name,"provinceId") VALUES (1,'Quận','Quận Ba Đình',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (2,'Quận','Quận Hoàn Kiếm',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (3,'Quận','Quận Tây Hồ',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (4,'Quận','Quận Long Biên',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (5,'Quận','Quận Cầu Giấy',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (6,'Quận','Quận Đống Đa',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (7,'Quận','Quận Hai Bà Trưng',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (8,'Quận','Quận Hoàng Mai',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (9,'Quận','Quận Thanh Xuân',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (16,'Huyện','Huyện Sóc Sơn',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (17,'Huyện','Huyện Đông Anh',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (18,'Huyện','Huyện Gia Lâm',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (19,'Quận','Quận Nam Từ Liêm',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (20,'Huyện','Huyện Thanh Trì',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (21,'Quận','Quận Bắc Từ Liêm',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (250,'Huyện','Huyện Mê Linh',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (268,'Quận','Quận Hà Đông',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (269,'Thị xã','Thị xã Sơn Tây',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (271,'Huyện','Huyện Ba Vì',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (272,'Huyện','Huyện Phúc Thọ',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (273,'Huyện','Huyện Đan Phượng',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (274,'Huyện','Huyện Hoài Đức',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (275,'Huyện','Huyện Quốc Oai',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (276,'Huyện','Huyện Thạch Thất',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (277,'Huyện','Huyện Chương Mỹ',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (278,'Huyện','Huyện Thanh Oai',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (279,'Huyện','Huyện Thường Tín',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (280,'Huyện','Huyện Phú Xuyên',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (281,'Huyện','Huyện Ứng Hòa',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (282,'Huyện','Huyện Mỹ Đức',1);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (24,'Thành phố','Thành phố Hà Giang',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (26,'Huyện','Huyện Đồng Văn',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (27,'Huyện','Huyện Mèo Vạc',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (28,'Huyện','Huyện Yên Minh',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (29,'Huyện','Huyện Quản Bạ',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (30,'Huyện','Huyện Vị Xuyên',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (31,'Huyện','Huyện Bắc Mê',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (32,'Huyện','Huyện Hoàng Su Phì',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (33,'Huyện','Huyện Xín Mần',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (34,'Huyện','Huyện Bắc Quang',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (35,'Huyện','Huyện Quang Bình',2);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (40,'Thành phố','Thành phố Cao Bằng',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (42,'Huyện','Huyện Bảo Lâm',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (43,'Huyện','Huyện Bảo Lạc',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (45,'Huyện','Huyện Hà Quảng',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (47,'Huyện','Huyện Trùng Khánh',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (48,'Huyện','Huyện Hạ Lang',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (49,'Huyện','Huyện Quảng Hòa',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (51,'Huyện','Huyện Hoà An',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (52,'Huyện','Huyện Nguyên Bình',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (53,'Huyện','Huyện Thạch An',4);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (58,'Thành phố','Thành Phố Bắc Kạn',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (60,'Huyện','Huyện Pác Nặm',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (61,'Huyện','Huyện Ba Bể',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (62,'Huyện','Huyện Ngân Sơn',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (63,'Huyện','Huyện Bạch Thông',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (64,'Huyện','Huyện Chợ Đồn',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (65,'Huyện','Huyện Chợ Mới',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (66,'Huyện','Huyện Na Rì',6);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (70,'Thành phố','Thành phố Tuyên Quang',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (71,'Huyện','Huyện Lâm Bình',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (72,'Huyện','Huyện Na Hang',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (73,'Huyện','Huyện Chiêm Hóa',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (74,'Huyện','Huyện Hàm Yên',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (75,'Huyện','Huyện Yên Sơn',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (76,'Huyện','Huyện Sơn Dương',8);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (80,'Thành phố','Thành phố Lào Cai',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (82,'Huyện','Huyện Bát Xát',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (83,'Huyện','Huyện Mường Khương',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (84,'Huyện','Huyện Si Ma Cai',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (85,'Huyện','Huyện Bắc Hà',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (86,'Huyện','Huyện Bảo Thắng',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (87,'Huyện','Huyện Bảo Yên',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (88,'Thị xã','Thị xã Sa Pa',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (89,'Huyện','Huyện Văn Bàn',10);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (94,'Thành phố','Thành phố Điện Biên Phủ',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (95,'Thị xã','Thị Xã Mường Lay',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (96,'Huyện','Huyện Mường Nhé',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (97,'Huyện','Huyện Mường Chà',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (98,'Huyện','Huyện Tủa Chùa',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (99,'Huyện','Huyện Tuần Giáo',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (100,'Huyện','Huyện Điện Biên',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (101,'Huyện','Huyện Điện Biên Đông',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (102,'Huyện','Huyện Mường Ảng',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (103,'Huyện','Huyện Nậm Pồ',11);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (105,'Thành phố','Thành phố Lai Châu',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (106,'Huyện','Huyện Tam Đường',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (107,'Huyện','Huyện Mường Tè',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (108,'Huyện','Huyện Sìn Hồ',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (109,'Huyện','Huyện Phong Thổ',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (110,'Huyện','Huyện Than Uyên',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (111,'Huyện','Huyện Tân Uyên',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (112,'Huyện','Huyện Nậm Nhùn',12);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (116,'Thành phố','Thành phố Sơn La',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (118,'Huyện','Huyện Quỳnh Nhai',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (119,'Huyện','Huyện Thuận Châu',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (120,'Huyện','Huyện Mường La',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (121,'Huyện','Huyện Bắc Yên',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (122,'Huyện','Huyện Phù Yên',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (123,'Huyện','Huyện Mộc Châu',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (124,'Huyện','Huyện Yên Châu',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (125,'Huyện','Huyện Mai Sơn',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (126,'Huyện','Huyện Sông Mã',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (127,'Huyện','Huyện Sốp Cộp',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (128,'Huyện','Huyện Vân Hồ',14);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (132,'Thành phố','Thành phố Yên Bái',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (133,'Thị xã','Thị xã Nghĩa Lộ',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (135,'Huyện','Huyện Lục Yên',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (136,'Huyện','Huyện Văn Yên',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (137,'Huyện','Huyện Mù Căng Chải',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (138,'Huyện','Huyện Trấn Yên',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (139,'Huyện','Huyện Trạm Tấu',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (140,'Huyện','Huyện Văn Chấn',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (141,'Huyện','Huyện Yên Bình',15);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (148,'Thành phố','Thành phố Hòa Bình',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (150,'Huyện','Huyện Đà Bắc',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (152,'Huyện','Huyện Lương Sơn',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (153,'Huyện','Huyện Kim Bôi',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (154,'Huyện','Huyện Cao Phong',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (155,'Huyện','Huyện Tân Lạc',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (156,'Huyện','Huyện Mai Châu',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (157,'Huyện','Huyện Lạc Sơn',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (158,'Huyện','Huyện Yên Thủy',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (159,'Huyện','Huyện Lạc Thủy',17);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (164,'Thành phố','Thành phố Thái Nguyên',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (165,'Thành phố','Thành phố Sông Công',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (167,'Huyện','Huyện Định Hóa',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (168,'Huyện','Huyện Phú Lương',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (169,'Huyện','Huyện Đồng Hỷ',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (170,'Huyện','Huyện Võ Nhai',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (171,'Huyện','Huyện Đại Từ',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (172,'Thị xã','Thị xã Phổ Yên',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (173,'Huyện','Huyện Phú Bình',19);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (178,'Thành phố','Thành phố Lạng Sơn',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (180,'Huyện','Huyện Tràng Định',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (181,'Huyện','Huyện Bình Gia',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (182,'Huyện','Huyện Văn Lãng',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (183,'Huyện','Huyện Cao Lộc',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (184,'Huyện','Huyện Văn Quan',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (185,'Huyện','Huyện Bắc Sơn',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (186,'Huyện','Huyện Hữu Lũng',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (187,'Huyện','Huyện Chi Lăng',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (188,'Huyện','Huyện Lộc Bình',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (189,'Huyện','Huyện Đình Lập',20);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (193,'Thành phố','Thành phố Hạ Long',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (194,'Thành phố','Thành phố Móng Cái',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (195,'Thành phố','Thành phố Cẩm Phả',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (196,'Thành phố','Thành phố Uông Bí',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (198,'Huyện','Huyện Bình Liêu',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (199,'Huyện','Huyện Tiên Yên',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (200,'Huyện','Huyện Đầm Hà',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (201,'Huyện','Huyện Hải Hà',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (202,'Huyện','Huyện Ba Chẽ',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (203,'Huyện','Huyện Vân Đồn',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (205,'Thị xã','Thị xã Đông Triều',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (206,'Thị xã','Thị xã Quảng Yên',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (207,'Huyện','Huyện Cô Tô',22);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (213,'Thành phố','Thành phố Bắc Giang',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (215,'Huyện','Huyện Yên Thế',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (216,'Huyện','Huyện Tân Yên',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (217,'Huyện','Huyện Lạng Giang',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (218,'Huyện','Huyện Lục Nam',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (219,'Huyện','Huyện Lục Ngạn',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (220,'Huyện','Huyện Sơn Động',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (221,'Huyện','Huyện Yên Dũng',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (222,'Huyện','Huyện Việt Yên',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (223,'Huyện','Huyện Hiệp Hòa',24);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (227,'Thành phố','Thành phố Việt Trì',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (228,'Thị xã','Thị xã Phú Thọ',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (230,'Huyện','Huyện Đoan Hùng',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (231,'Huyện','Huyện Hạ Hoà',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (232,'Huyện','Huyện Thanh Ba',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (233,'Huyện','Huyện Phù Ninh',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (234,'Huyện','Huyện Yên Lập',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (235,'Huyện','Huyện Cẩm Khê',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (236,'Huyện','Huyện Tam Nông',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (237,'Huyện','Huyện Lâm Thao',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (238,'Huyện','Huyện Thanh Sơn',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (239,'Huyện','Huyện Thanh Thuỷ',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (240,'Huyện','Huyện Tân Sơn',25);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (243,'Thành phố','Thành phố Vĩnh Yên',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (244,'Thành phố','Thành phố Phúc Yên',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (246,'Huyện','Huyện Lập Thạch',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (247,'Huyện','Huyện Tam Dương',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (248,'Huyện','Huyện Tam Đảo',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (249,'Huyện','Huyện Bình Xuyên',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (251,'Huyện','Huyện Yên Lạc',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (252,'Huyện','Huyện Vĩnh Tường',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (253,'Huyện','Huyện Sông Lô',26);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (256,'Thành phố','Thành phố Bắc Ninh',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (258,'Huyện','Huyện Yên Phong',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (259,'Huyện','Huyện Quế Võ',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (260,'Huyện','Huyện Tiên Du',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (261,'Thị xã','Thị xã Từ Sơn',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (262,'Huyện','Huyện Thuận Thành',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (263,'Huyện','Huyện Gia Bình',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (264,'Huyện','Huyện Lương Tài',27);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (288,'Thành phố','Thành phố Hải Dương',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (290,'Thành phố','Thành phố Chí Linh',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (291,'Huyện','Huyện Nam Sách',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (292,'Thị xã','Thị xã Kinh Môn',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (293,'Huyện','Huyện Kim Thành',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (294,'Huyện','Huyện Thanh Hà',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (295,'Huyện','Huyện Cẩm Giàng',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (296,'Huyện','Huyện Bình Giang',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (297,'Huyện','Huyện Gia Lộc',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (298,'Huyện','Huyện Tứ Kỳ',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (299,'Huyện','Huyện Ninh Giang',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (300,'Huyện','Huyện Thanh Miện',30);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (303,'Quận','Quận Hồng Bàng',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (304,'Quận','Quận Ngô Quyền',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (305,'Quận','Quận Lê Chân',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (306,'Quận','Quận Hải An',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (307,'Quận','Quận Kiến An',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (308,'Quận','Quận Đồ Sơn',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (309,'Quận','Quận Dương Kinh',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (311,'Huyện','Huyện Thuỷ Nguyên',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (312,'Huyện','Huyện An Dương',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (313,'Huyện','Huyện An Lão',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (314,'Huyện','Huyện Kiến Thuỵ',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (315,'Huyện','Huyện Tiên Lãng',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (316,'Huyện','Huyện Vĩnh Bảo',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (317,'Huyện','Huyện Cát Hải',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (318,'Huyện','Huyện Bạch Long Vĩ',31);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (323,'Thành phố','Thành phố Hưng Yên',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (325,'Huyện','Huyện Văn Lâm',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (326,'Huyện','Huyện Văn Giang',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (327,'Huyện','Huyện Yên Mỹ',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (328,'Thị xã','Thị xã Mỹ Hào',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (329,'Huyện','Huyện Ân Thi',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (330,'Huyện','Huyện Khoái Châu',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (331,'Huyện','Huyện Kim Động',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (332,'Huyện','Huyện Tiên Lữ',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (333,'Huyện','Huyện Phù Cừ',33);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (336,'Thành phố','Thành phố Thái Bình',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (338,'Huyện','Huyện Quỳnh Phụ',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (339,'Huyện','Huyện Hưng Hà',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (340,'Huyện','Huyện Đông Hưng',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (341,'Huyện','Huyện Thái Thụy',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (342,'Huyện','Huyện Tiền Hải',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (343,'Huyện','Huyện Kiến Xương',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (344,'Huyện','Huyện Vũ Thư',34);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (347,'Thành phố','Thành phố Phủ Lý',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (349,'Thị xã','Thị xã Duy Tiên',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (350,'Huyện','Huyện Kim Bảng',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (351,'Huyện','Huyện Thanh Liêm',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (352,'Huyện','Huyện Bình Lục',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (353,'Huyện','Huyện Lý Nhân',35);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (356,'Thành phố','Thành phố Nam Định',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (358,'Huyện','Huyện Mỹ Lộc',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (359,'Huyện','Huyện Vụ Bản',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (360,'Huyện','Huyện Ý Yên',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (361,'Huyện','Huyện Nghĩa Hưng',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (362,'Huyện','Huyện Nam Trực',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (363,'Huyện','Huyện Trực Ninh',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (364,'Huyện','Huyện Xuân Trường',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (365,'Huyện','Huyện Giao Thủy',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (366,'Huyện','Huyện Hải Hậu',36);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (369,'Thành phố','Thành phố Ninh Bình',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (370,'Thành phố','Thành phố Tam Điệp',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (372,'Huyện','Huyện Nho Quan',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (373,'Huyện','Huyện Gia Viễn',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (374,'Huyện','Huyện Hoa Lư',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (375,'Huyện','Huyện Yên Khánh',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (376,'Huyện','Huyện Kim Sơn',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (377,'Huyện','Huyện Yên Mô',37);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (380,'Thành phố','Thành phố Thanh Hóa',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (381,'Thị xã','Thị xã Bỉm Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (382,'Thành phố','Thành phố Sầm Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (384,'Huyện','Huyện Mường Lát',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (385,'Huyện','Huyện Quan Hóa',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (386,'Huyện','Huyện Bá Thước',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (387,'Huyện','Huyện Quan Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (388,'Huyện','Huyện Lang Chánh',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (389,'Huyện','Huyện Ngọc Lặc',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (390,'Huyện','Huyện Cẩm Thủy',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (391,'Huyện','Huyện Thạch Thành',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (392,'Huyện','Huyện Hà Trung',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (393,'Huyện','Huyện Vĩnh Lộc',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (394,'Huyện','Huyện Yên Định',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (395,'Huyện','Huyện Thọ Xuân',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (396,'Huyện','Huyện Thường Xuân',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (397,'Huyện','Huyện Triệu Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (398,'Huyện','Huyện Thiệu Hóa',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (399,'Huyện','Huyện Hoằng Hóa',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (400,'Huyện','Huyện Hậu Lộc',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (401,'Huyện','Huyện Nga Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (402,'Huyện','Huyện Như Xuân',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (403,'Huyện','Huyện Như Thanh',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (404,'Huyện','Huyện Nông Cống',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (405,'Huyện','Huyện Đông Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (406,'Huyện','Huyện Quảng Xương',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (407,'Thị xã','Thị xã Nghi Sơn',38);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (412,'Thành phố','Thành phố Vinh',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (413,'Thị xã','Thị xã Cửa Lò',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (414,'Thị xã','Thị xã Thái Hoà',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (415,'Huyện','Huyện Quế Phong',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (416,'Huyện','Huyện Quỳ Châu',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (417,'Huyện','Huyện Kỳ Sơn',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (418,'Huyện','Huyện Tương Dương',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (419,'Huyện','Huyện Nghĩa Đàn',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (420,'Huyện','Huyện Quỳ Hợp',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (421,'Huyện','Huyện Quỳnh Lưu',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (422,'Huyện','Huyện Con Cuông',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (423,'Huyện','Huyện Tân Kỳ',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (424,'Huyện','Huyện Anh Sơn',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (425,'Huyện','Huyện Diễn Châu',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (426,'Huyện','Huyện Yên Thành',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (427,'Huyện','Huyện Đô Lương',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (428,'Huyện','Huyện Thanh Chương',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (429,'Huyện','Huyện Nghi Lộc',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (430,'Huyện','Huyện Nam Đàn',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (431,'Huyện','Huyện Hưng Nguyên',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (432,'Thị xã','Thị xã Hoàng Mai',40);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (436,'Thành phố','Thành phố Hà Tĩnh',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (437,'Thị xã','Thị xã Hồng Lĩnh',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (439,'Huyện','Huyện Hương Sơn',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (440,'Huyện','Huyện Đức Thọ',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (441,'Huyện','Huyện Vũ Quang',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (442,'Huyện','Huyện Nghi Xuân',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (443,'Huyện','Huyện Can Lộc',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (444,'Huyện','Huyện Hương Khê',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (445,'Huyện','Huyện Thạch Hà',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (446,'Huyện','Huyện Cẩm Xuyên',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (447,'Huyện','Huyện Kỳ Anh',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (448,'Huyện','Huyện Lộc Hà',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (449,'Thị xã','Thị xã Kỳ Anh',42);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (450,'Thành phố','Thành Phố Đồng Hới',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (452,'Huyện','Huyện Minh Hóa',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (453,'Huyện','Huyện Tuyên Hóa',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (454,'Huyện','Huyện Quảng Trạch',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (455,'Huyện','Huyện Bố Trạch',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (456,'Huyện','Huyện Quảng Ninh',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (457,'Huyện','Huyện Lệ Thủy',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (458,'Thị xã','Thị xã Ba Đồn',44);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (461,'Thành phố','Thành phố Đông Hà',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (462,'Thị xã','Thị xã Quảng Trị',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (464,'Huyện','Huyện Vĩnh Linh',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (465,'Huyện','Huyện Hướng Hóa',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (466,'Huyện','Huyện Gio Linh',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (467,'Huyện','Huyện Đa Krông',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (468,'Huyện','Huyện Cam Lộ',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (469,'Huyện','Huyện Triệu Phong',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (470,'Huyện','Huyện Hải Lăng',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (471,'Huyện','Huyện Cồn Cỏ',45);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (474,'Thành phố','Thành phố Huế',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (476,'Huyện','Huyện Phong Điền',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (477,'Huyện','Huyện Quảng Điền',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (478,'Huyện','Huyện Phú Vang',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (479,'Thị xã','Thị xã Hương Thủy',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (480,'Thị xã','Thị xã Hương Trà',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (481,'Huyện','Huyện A Lưới',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (482,'Huyện','Huyện Phú Lộc',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (483,'Huyện','Huyện Nam Đông',46);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (490,'Quận','Quận Liên Chiểu',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (491,'Quận','Quận Thanh Khê',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (492,'Quận','Quận Hải Châu',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (493,'Quận','Quận Sơn Trà',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (494,'Quận','Quận Ngũ Hành Sơn',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (495,'Quận','Quận Cẩm Lệ',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (497,'Huyện','Huyện Hòa Vang',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (498,'Huyện','Huyện Hoàng Sa',48);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (502,'Thành phố','Thành phố Tam Kỳ',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (503,'Thành phố','Thành phố Hội An',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (504,'Huyện','Huyện Tây Giang',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (505,'Huyện','Huyện Đông Giang',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (506,'Huyện','Huyện Đại Lộc',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (507,'Thị xã','Thị xã Điện Bàn',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (508,'Huyện','Huyện Duy Xuyên',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (509,'Huyện','Huyện Quế Sơn',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (510,'Huyện','Huyện Nam Giang',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (511,'Huyện','Huyện Phước Sơn',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (512,'Huyện','Huyện Hiệp Đức',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (513,'Huyện','Huyện Thăng Bình',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (514,'Huyện','Huyện Tiên Phước',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (515,'Huyện','Huyện Bắc Trà My',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (516,'Huyện','Huyện Nam Trà My',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (517,'Huyện','Huyện Núi Thành',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (518,'Huyện','Huyện Phú Ninh',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (519,'Huyện','Huyện Nông Sơn',49);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (522,'Thành phố','Thành phố Quảng Ngãi',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (524,'Huyện','Huyện Bình Sơn',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (525,'Huyện','Huyện Trà Bồng',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (527,'Huyện','Huyện Sơn Tịnh',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (528,'Huyện','Huyện Tư Nghĩa',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (529,'Huyện','Huyện Sơn Hà',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (530,'Huyện','Huyện Sơn Tây',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (531,'Huyện','Huyện Minh Long',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (532,'Huyện','Huyện Nghĩa Hành',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (533,'Huyện','Huyện Mộ Đức',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (534,'Thị xã','Thị xã Đức Phổ',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (535,'Huyện','Huyện Ba Tơ',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (536,'Huyện','Huyện Lý Sơn',51);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (540,'Thành phố','Thành phố Quy Nhơn',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (542,'Huyện','Huyện An Lão',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (543,'Thị xã','Thị xã Hoài Nhơn',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (544,'Huyện','Huyện Hoài Ân',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (545,'Huyện','Huyện Phù Mỹ',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (546,'Huyện','Huyện Vĩnh Thạnh',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (547,'Huyện','Huyện Tây Sơn',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (548,'Huyện','Huyện Phù Cát',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (549,'Thị xã','Thị xã An Nhơn',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (550,'Huyện','Huyện Tuy Phước',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (551,'Huyện','Huyện Vân Canh',52);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (555,'Thành phố','Thành phố Tuy Hoà',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (557,'Thị xã','Thị xã Sông Cầu',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (558,'Huyện','Huyện Đồng Xuân',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (559,'Huyện','Huyện Tuy An',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (560,'Huyện','Huyện Sơn Hòa',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (561,'Huyện','Huyện Sông Hinh',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (562,'Huyện','Huyện Tây Hoà',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (563,'Huyện','Huyện Phú Hoà',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (564,'Thị xã','Thị xã Đông Hòa',54);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (568,'Thành phố','Thành phố Nha Trang',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (569,'Thành phố','Thành phố Cam Ranh',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (570,'Huyện','Huyện Cam Lâm',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (571,'Huyện','Huyện Vạn Ninh',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (572,'Thị xã','Thị xã Ninh Hòa',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (573,'Huyện','Huyện Khánh Vĩnh',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (574,'Huyện','Huyện Diên Khánh',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (575,'Huyện','Huyện Khánh Sơn',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (576,'Huyện','Huyện Trường Sa',56);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (582,'Thành phố','Thành phố Phan Rang-Tháp Chàm',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (584,'Huyện','Huyện Bác Ái',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (585,'Huyện','Huyện Ninh Sơn',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (586,'Huyện','Huyện Ninh Hải',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (587,'Huyện','Huyện Ninh Phước',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (588,'Huyện','Huyện Thuận Bắc',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (589,'Huyện','Huyện Thuận Nam',58);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (593,'Thành phố','Thành phố Phan Thiết',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (594,'Thị xã','Thị xã La Gi',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (595,'Huyện','Huyện Tuy Phong',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (596,'Huyện','Huyện Bắc Bình',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (597,'Huyện','Huyện Hàm Thuận Bắc',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (598,'Huyện','Huyện Hàm Thuận Nam',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (599,'Huyện','Huyện Tánh Linh',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (600,'Huyện','Huyện Đức Linh',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (601,'Huyện','Huyện Hàm Tân',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (602,'Huyện','Huyện Phú Quí',60);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (608,'Thành phố','Thành phố Kon Tum',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (610,'Huyện','Huyện Đắk Glei',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (611,'Huyện','Huyện Ngọc Hồi',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (612,'Huyện','Huyện Đắk Tô',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (613,'Huyện','Huyện Kon Plông',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (614,'Huyện','Huyện Kon Rẫy',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (615,'Huyện','Huyện Đắk Hà',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (616,'Huyện','Huyện Sa Thầy',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (617,'Huyện','Huyện Tu Mơ Rông',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (618,'Huyện',E'Huyện Ia H\' Drai',62);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (622,'Thành phố','Thành phố Pleiku',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (623,'Thị xã','Thị xã An Khê',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (624,'Thị xã','Thị xã Ayun Pa',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (625,'Huyện','Huyện KBang',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (626,'Huyện','Huyện Đăk Đoa',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (627,'Huyện','Huyện Chư Păh',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (628,'Huyện','Huyện Ia Grai',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (629,'Huyện','Huyện Mang Yang',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (630,'Huyện','Huyện Kông Chro',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (631,'Huyện','Huyện Đức Cơ',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (632,'Huyện','Huyện Chư Prông',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (633,'Huyện','Huyện Chư Sê',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (634,'Huyện','Huyện Đăk Pơ',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (635,'Huyện','Huyện Ia Pa',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (637,'Huyện','Huyện Krông Pa',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (638,'Huyện','Huyện Phú Thiện',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (639,'Huyện','Huyện Chư Pưh',64);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (643,'Thành phố','Thành phố Buôn Ma Thuột',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (644,'Thị xã','Thị Xã Buôn Hồ',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (645,'Huyện',E'Huyện Ea H\'leo',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (646,'Huyện','Huyện Ea Súp',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (647,'Huyện','Huyện Buôn Đôn',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (648,'Huyện',E'Huyện Cư M\'gar',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (649,'Huyện','Huyện Krông Búk',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (650,'Huyện','Huyện Krông Năng',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (651,'Huyện','Huyện Ea Kar',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (652,'Huyện',E'Huyện M\'Đrắk',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (653,'Huyện','Huyện Krông Bông',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (654,'Huyện','Huyện Krông Pắc',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (655,'Huyện','Huyện Krông A Na',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (656,'Huyện','Huyện Lắk',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (657,'Huyện','Huyện Cư Kuin',66);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (660,'Thành phố','Thành phố Gia Nghĩa',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (661,'Huyện','Huyện Đăk Glong',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (662,'Huyện','Huyện Cư Jút',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (663,'Huyện','Huyện Đắk Mil',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (664,'Huyện','Huyện Krông Nô',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (665,'Huyện','Huyện Đắk Song',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (666,'Huyện',E'Huyện Đắk R\'Lấp',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (667,'Huyện','Huyện Tuy Đức',67);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (672,'Thành phố','Thành phố Đà Lạt',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (673,'Thành phố','Thành phố Bảo Lộc',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (674,'Huyện','Huyện Đam Rông',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (675,'Huyện','Huyện Lạc Dương',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (676,'Huyện','Huyện Lâm Hà',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (677,'Huyện','Huyện Đơn Dương',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (678,'Huyện','Huyện Đức Trọng',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (679,'Huyện','Huyện Di Linh',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (680,'Huyện','Huyện Bảo Lâm',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (681,'Huyện','Huyện Đạ Huoai',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (682,'Huyện','Huyện Đạ Tẻh',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (683,'Huyện','Huyện Cát Tiên',68);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (688,'Thị xã','Thị xã Phước Long',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (689,'Thành phố','Thành phố Đồng Xoài',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (690,'Thị xã','Thị xã Bình Long',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (691,'Huyện','Huyện Bù Gia Mập',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (692,'Huyện','Huyện Lộc Ninh',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (693,'Huyện','Huyện Bù Đốp',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (694,'Huyện','Huyện Hớn Quản',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (695,'Huyện','Huyện Đồng Phú',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (696,'Huyện','Huyện Bù Đăng',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (697,'Huyện','Huyện Chơn Thành',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (698,'Huyện','Huyện Phú Riềng',70);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (703,'Thành phố','Thành phố Tây Ninh',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (705,'Huyện','Huyện Tân Biên',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (706,'Huyện','Huyện Tân Châu',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (707,'Huyện','Huyện Dương Minh Châu',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (708,'Huyện','Huyện Châu Thành',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (709,'Thị xã','Thị xã Hòa Thành',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (710,'Huyện','Huyện Gò Dầu',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (711,'Huyện','Huyện Bến Cầu',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (712,'Thị xã','Thị xã Trảng Bàng',72);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (718,'Thành phố','Thành phố Thủ Dầu Một',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (719,'Huyện','Huyện Bàu Bàng',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (720,'Huyện','Huyện Dầu Tiếng',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (721,'Thị xã','Thị xã Bến Cát',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (722,'Huyện','Huyện Phú Giáo',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (723,'Thị xã','Thị xã Tân Uyên',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (724,'Thành phố','Thành phố Dĩ An',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (725,'Thành phố','Thành phố Thuận An',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (726,'Huyện','Huyện Bắc Tân Uyên',74);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (731,'Thành phố','Thành phố Biên Hòa',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (732,'Thành phố','Thành phố Long Khánh',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (734,'Huyện','Huyện Tân Phú',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (735,'Huyện','Huyện Vĩnh Cửu',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (736,'Huyện','Huyện Định Quán',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (737,'Huyện','Huyện Trảng Bom',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (738,'Huyện','Huyện Thống Nhất',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (739,'Huyện','Huyện Cẩm Mỹ',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (740,'Huyện','Huyện Long Thành',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (741,'Huyện','Huyện Xuân Lộc',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (742,'Huyện','Huyện Nhơn Trạch',75);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (747,'Thành phố','Thành phố Vũng Tàu',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (748,'Thành phố','Thành phố Bà Rịa',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (750,'Huyện','Huyện Châu Đức',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (751,'Huyện','Huyện Xuyên Mộc',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (752,'Huyện','Huyện Long Điền',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (753,'Huyện','Huyện Đất Đỏ',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (754,'Thị xã','Thị xã Phú Mỹ',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (755,'Huyện','Huyện Côn Đảo',77);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (760,'Quận','Quận 1',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (761,'Quận','Quận 12',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (764,'Quận','Quận Gò Vấp',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (765,'Quận','Quận Bình Thạnh',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (766,'Quận','Quận Tân Bình',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (767,'Quận','Quận Tân Phú',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (768,'Quận','Quận Phú Nhuận',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (769,'Thành phố','Thành phố Thủ Đức',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (770,'Quận','Quận 3',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (771,'Quận','Quận 10',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (772,'Quận','Quận 11',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (773,'Quận','Quận 4',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (774,'Quận','Quận 5',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (775,'Quận','Quận 6',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (776,'Quận','Quận 8',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (777,'Quận','Quận Bình Tân',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (778,'Quận','Quận 7',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (783,'Huyện','Huyện Củ Chi',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (784,'Huyện','Huyện Hóc Môn',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (785,'Huyện','Huyện Bình Chánh',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (786,'Huyện','Huyện Nhà Bè',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (787,'Huyện','Huyện Cần Giờ',79);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (794,'Thành phố','Thành phố Tân An',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (795,'Thị xã','Thị xã Kiến Tường',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (796,'Huyện','Huyện Tân Hưng',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (797,'Huyện','Huyện Vĩnh Hưng',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (798,'Huyện','Huyện Mộc Hóa',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (799,'Huyện','Huyện Tân Thạnh',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (800,'Huyện','Huyện Thạnh Hóa',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (801,'Huyện','Huyện Đức Huệ',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (802,'Huyện','Huyện Đức Hòa',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (803,'Huyện','Huyện Bến Lức',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (804,'Huyện','Huyện Thủ Thừa',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (805,'Huyện','Huyện Tân Trụ',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (806,'Huyện','Huyện Cần Đước',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (807,'Huyện','Huyện Cần Giuộc',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (808,'Huyện','Huyện Châu Thành',80);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (815,'Thành phố','Thành phố Mỹ Tho',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (816,'Thị xã','Thị xã Gò Công',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (817,'Thị xã','Thị xã Cai Lậy',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (818,'Huyện','Huyện Tân Phước',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (819,'Huyện','Huyện Cái Bè',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (820,'Huyện','Huyện Cai Lậy',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (821,'Huyện','Huyện Châu Thành',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (822,'Huyện','Huyện Chợ Gạo',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (823,'Huyện','Huyện Gò Công Tây',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (824,'Huyện','Huyện Gò Công Đông',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (825,'Huyện','Huyện Tân Phú Đông',82);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (829,'Thành phố','Thành phố Bến Tre',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (831,'Huyện','Huyện Châu Thành',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (832,'Huyện','Huyện Chợ Lách',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (833,'Huyện','Huyện Mỏ Cày Nam',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (834,'Huyện','Huyện Giồng Trôm',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (835,'Huyện','Huyện Bình Đại',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (836,'Huyện','Huyện Ba Tri',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (837,'Huyện','Huyện Thạnh Phú',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (838,'Huyện','Huyện Mỏ Cày Bắc',83);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (842,'Thành phố','Thành phố Trà Vinh',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (844,'Huyện','Huyện Càng Long',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (845,'Huyện','Huyện Cầu Kè',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (846,'Huyện','Huyện Tiểu Cần',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (847,'Huyện','Huyện Châu Thành',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (848,'Huyện','Huyện Cầu Ngang',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (849,'Huyện','Huyện Trà Cú',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (850,'Huyện','Huyện Duyên Hải',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (851,'Thị xã','Thị xã Duyên Hải',84);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (855,'Thành phố','Thành phố Vĩnh Long',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (857,'Huyện','Huyện Long Hồ',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (858,'Huyện','Huyện Mang Thít',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (859,'Huyện','Huyện  Vũng Liêm',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (860,'Huyện','Huyện Tam Bình',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (861,'Thị xã','Thị xã Bình Minh',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (862,'Huyện','Huyện Trà Ôn',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (863,'Huyện','Huyện Bình Tân',86);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (866,'Thành phố','Thành phố Cao Lãnh',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (867,'Thành phố','Thành phố Sa Đéc',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (868,'Thành phố','Thành phố Hồng Ngự',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (869,'Huyện','Huyện Tân Hồng',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (870,'Huyện','Huyện Hồng Ngự',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (871,'Huyện','Huyện Tam Nông',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (872,'Huyện','Huyện Tháp Mười',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (873,'Huyện','Huyện Cao Lãnh',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (874,'Huyện','Huyện Thanh Bình',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (875,'Huyện','Huyện Lấp Vò',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (876,'Huyện','Huyện Lai Vung',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (877,'Huyện','Huyện Châu Thành',87);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (883,'Thành phố','Thành phố Long Xuyên',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (884,'Thành phố','Thành phố Châu Đốc',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (886,'Huyện','Huyện An Phú',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (887,'Thị xã','Thị xã Tân Châu',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (888,'Huyện','Huyện Phú Tân',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (889,'Huyện','Huyện Châu Phú',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (890,'Huyện','Huyện Tịnh Biên',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (891,'Huyện','Huyện Tri Tôn',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (892,'Huyện','Huyện Châu Thành',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (893,'Huyện','Huyện Chợ Mới',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (894,'Huyện','Huyện Thoại Sơn',89);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (899,'Thành phố','Thành phố Rạch Giá',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (900,'Thành phố','Thành phố Hà Tiên',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (902,'Huyện','Huyện Kiên Lương',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (903,'Huyện','Huyện Hòn Đất',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (904,'Huyện','Huyện Tân Hiệp',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (905,'Huyện','Huyện Châu Thành',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (906,'Huyện','Huyện Giồng Riềng',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (907,'Huyện','Huyện Gò Quao',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (908,'Huyện','Huyện An Biên',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (909,'Huyện','Huyện An Minh',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (910,'Huyện','Huyện Vĩnh Thuận',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (911,'Thành phố','Thành phố Phú Quốc',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (912,'Huyện','Huyện Kiên Hải',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (913,'Huyện','Huyện U Minh Thượng',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (914,'Huyện','Huyện Giang Thành',91);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (916,'Quận','Quận Ninh Kiều',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (917,'Quận','Quận Ô Môn',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (918,'Quận','Quận Bình Thuỷ',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (919,'Quận','Quận Cái Răng',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (923,'Quận','Quận Thốt Nốt',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (924,'Huyện','Huyện Vĩnh Thạnh',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (925,'Huyện','Huyện Cờ Đỏ',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (926,'Huyện','Huyện Phong Điền',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (927,'Huyện','Huyện Thới Lai',92);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (930,'Thành phố','Thành phố Vị Thanh',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (931,'Thành phố','Thành phố Ngã Bảy',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (932,'Huyện','Huyện Châu Thành A',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (933,'Huyện','Huyện Châu Thành',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (934,'Huyện','Huyện Phụng Hiệp',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (935,'Huyện','Huyện Vị Thuỷ',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (936,'Huyện','Huyện Long Mỹ',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (937,'Thị xã','Thị xã Long Mỹ',93);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (941,'Thành phố','Thành phố Sóc Trăng',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (942,'Huyện','Huyện Châu Thành',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (943,'Huyện','Huyện Kế Sách',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (944,'Huyện','Huyện Mỹ Tú',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (945,'Huyện','Huyện Cù Lao Dung',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (946,'Huyện','Huyện Long Phú',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (947,'Huyện','Huyện Mỹ Xuyên',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (948,'Thị xã','Thị xã Ngã Năm',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (949,'Huyện','Huyện Thạnh Trị',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (950,'Thị xã','Thị xã Vĩnh Châu',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (951,'Huyện','Huyện Trần Đề',94);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (954,'Thành phố','Thành phố Bạc Liêu',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (956,'Huyện','Huyện Hồng Dân',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (957,'Huyện','Huyện Phước Long',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (958,'Huyện','Huyện Vĩnh Lợi',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (959,'Thị xã','Thị xã Giá Rai',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (960,'Huyện','Huyện Đông Hải',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (961,'Huyện','Huyện Hoà Bình',95);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (964,'Thành phố','Thành phố Cà Mau',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (966,'Huyện','Huyện U Minh',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (967,'Huyện','Huyện Thới Bình',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (968,'Huyện','Huyện Trần Văn Thời',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (969,'Huyện','Huyện Cái Nước',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (970,'Huyện','Huyện Đầm Dơi',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (971,'Huyện','Huyện Năm Căn',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (972,'Huyện','Huyện Phú Tân',96);
INSERT INTO public."District"(id, type, name,"provinceId") VALUES (973,'Huyện','Huyện Ngọc Hiển',96);
