INSERT INTO public."Province"(id, type, name) VALUES (1,'Thành phố Trung ương','Thành phố Hà Nội');
INSERT INTO public."Province"(id, type, name) VALUES (2,'Tỉnh','Tỉnh Hà Giang');
INSERT INTO public."Province"(id, type, name) VALUES (4,'Tỉnh','Tỉnh Cao Bằng');
INSERT INTO public."Province"(id, type, name) VALUES (6,'Tỉnh','Tỉnh Bắc Kạn');
INSERT INTO public."Province"(id, type, name) VALUES (8,'Tỉnh','Tỉnh Tuyên Quang');
INSERT INTO public."Province"(id, type, name) VALUES (10,'Tỉnh','Tỉnh Lào Cai');
INSERT INTO public."Province"(id, type, name) VALUES (11,'Tỉnh','Tỉnh Điện Biên');
INSERT INTO public."Province"(id, type, name) VALUES (12,'Tỉnh','Tỉnh Lai Châu');
INSERT INTO public."Province"(id, type, name) VALUES (14,'Tỉnh','Tỉnh Sơn La');
INSERT INTO public."Province"(id, type, name) VALUES (15,'Tỉnh','Tỉnh Yên Bái');
INSERT INTO public."Province"(id, type, name) VALUES (17,'Tỉnh','Tỉnh Hoà Bình');
INSERT INTO public."Province"(id, type, name) VALUES (19,'Tỉnh','Tỉnh Thái Nguyên');
INSERT INTO public."Province"(id, type, name) VALUES (20,'Tỉnh','Tỉnh Lạng Sơn');
INSERT INTO public."Province"(id, type, name) VALUES (22,'Tỉnh','Tỉnh Quảng Ninh');
INSERT INTO public."Province"(id, type, name) VALUES (24,'Tỉnh','Tỉnh Bắc Giang');
INSERT INTO public."Province"(id, type, name) VALUES (25,'Tỉnh','Tỉnh Phú Thọ');
INSERT INTO public."Province"(id, type, name) VALUES (26,'Tỉnh','Tỉnh Vĩnh Phúc');
INSERT INTO public."Province"(id, type, name) VALUES (27,'Tỉnh','Tỉnh Bắc Ninh');
INSERT INTO public."Province"(id, type, name) VALUES (30,'Tỉnh','Tỉnh Hải Dương');
INSERT INTO public."Province"(id, type, name) VALUES (31,'Thành phố Trung ương','Thành phố Hải Phòng');
INSERT INTO public."Province"(id, type, name) VALUES (33,'Tỉnh','Tỉnh Hưng Yên');
INSERT INTO public."Province"(id, type, name) VALUES (34,'Tỉnh','Tỉnh Thái Bình');
INSERT INTO public."Province"(id, type, name) VALUES (35,'Tỉnh','Tỉnh Hà Nam');
INSERT INTO public."Province"(id, type, name) VALUES (36,'Tỉnh','Tỉnh Nam Định');
INSERT INTO public."Province"(id, type, name) VALUES (37,'Tỉnh','Tỉnh Ninh Bình');
INSERT INTO public."Province"(id, type, name) VALUES (38,'Tỉnh','Tỉnh Thanh Hóa');
INSERT INTO public."Province"(id, type, name) VALUES (40,'Tỉnh','Tỉnh Nghệ An');
INSERT INTO public."Province"(id, type, name) VALUES (42,'Tỉnh','Tỉnh Hà Tĩnh');
INSERT INTO public."Province"(id, type, name) VALUES (44,'Tỉnh','Tỉnh Quảng Bình');
INSERT INTO public."Province"(id, type, name) VALUES (45,'Tỉnh','Tỉnh Quảng Trị');
INSERT INTO public."Province"(id, type, name) VALUES (46,'Tỉnh','Tỉnh Thừa Thiên Huế');
INSERT INTO public."Province"(id, type, name) VALUES (48,'Thành phố Trung ương','Thành phố Đà Nẵng');
INSERT INTO public."Province"(id, type, name) VALUES (49,'Tỉnh','Tỉnh Quảng Nam');
INSERT INTO public."Province"(id, type, name) VALUES (51,'Tỉnh','Tỉnh Quảng Ngãi');
INSERT INTO public."Province"(id, type, name) VALUES (52,'Tỉnh','Tỉnh Bình Định');
INSERT INTO public."Province"(id, type, name) VALUES (54,'Tỉnh','Tỉnh Phú Yên');
INSERT INTO public."Province"(id, type, name) VALUES (56,'Tỉnh','Tỉnh Khánh Hòa');
INSERT INTO public."Province"(id, type, name) VALUES (58,'Tỉnh','Tỉnh Ninh Thuận');
INSERT INTO public."Province"(id, type, name) VALUES (60,'Tỉnh','Tỉnh Bình Thuận');
INSERT INTO public."Province"(id, type, name) VALUES (62,'Tỉnh','Tỉnh Kon Tum');
INSERT INTO public."Province"(id, type, name) VALUES (64,'Tỉnh','Tỉnh Gia Lai');
INSERT INTO public."Province"(id, type, name) VALUES (66,'Tỉnh','Tỉnh Đắk Lắk');
INSERT INTO public."Province"(id, type, name) VALUES (67,'Tỉnh','Tỉnh Đắk Nông');
INSERT INTO public."Province"(id, type, name) VALUES (68,'Tỉnh','Tỉnh Lâm Đồng');
INSERT INTO public."Province"(id, type, name) VALUES (70,'Tỉnh','Tỉnh Bình Phước');
INSERT INTO public."Province"(id, type, name) VALUES (72,'Tỉnh','Tỉnh Tây Ninh');
INSERT INTO public."Province"(id, type, name) VALUES (74,'Tỉnh','Tỉnh Bình Dương');
INSERT INTO public."Province"(id, type, name) VALUES (75,'Tỉnh','Tỉnh Đồng Nai');
INSERT INTO public."Province"(id, type, name) VALUES (77,'Tỉnh','Tỉnh Bà Rịa - Vũng Tàu');
INSERT INTO public."Province"(id, type, name) VALUES (79,'Thành phố Trung ương','Thành phố Hồ Chí Minh');
INSERT INTO public."Province"(id, type, name) VALUES (80,'Tỉnh','Tỉnh Long An');
INSERT INTO public."Province"(id, type, name) VALUES (82,'Tỉnh','Tỉnh Tiền Giang');
INSERT INTO public."Province"(id, type, name) VALUES (83,'Tỉnh','Tỉnh Bến Tre');
INSERT INTO public."Province"(id, type, name) VALUES (84,'Tỉnh','Tỉnh Trà Vinh');
INSERT INTO public."Province"(id, type, name) VALUES (86,'Tỉnh','Tỉnh Vĩnh Long');
INSERT INTO public."Province"(id, type, name) VALUES (87,'Tỉnh','Tỉnh Đồng Tháp');
INSERT INTO public."Province"(id, type, name) VALUES (89,'Tỉnh','Tỉnh An Giang');
INSERT INTO public."Province"(id, type, name) VALUES (91,'Tỉnh','Tỉnh Kiên Giang');
INSERT INTO public."Province"(id, type, name) VALUES (92,'Thành phố Trung ương','Thành phố Cần Thơ');
INSERT INTO public."Province"(id, type, name) VALUES (93,'Tỉnh','Tỉnh Hậu Giang');
INSERT INTO public."Province"(id, type, name) VALUES (94,'Tỉnh','Tỉnh Sóc Trăng');
INSERT INTO public."Province"(id, type, name) VALUES (95,'Tỉnh','Tỉnh Bạc Liêu');
INSERT INTO public."Province"(id, type, name) VALUES (96,'Tỉnh','Tỉnh Cà Mau');
